package com.qf.mapper;

import com.qf.pojo.MemberLoginLog;

public interface MemberLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int insert(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int insertSelective(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    MemberLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_login_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberLoginLog record);
}