package com.qf.mapper;

import com.qf.pojo.MemberCar;

public interface MemberCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int insert(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int insertSelective(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    MemberCar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberCar record);
}