package com.qf.mapper;

import com.qf.pojo.MemberProfile;

public interface MemberProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int insert(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int insertSelective(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    MemberProfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberProfile record);
}